name: Build and Push to ACR

on:
  push:
    branches:
      - main
  workflow_dispatch:   # ← pozwala uruchomić ręcznie z GitHub GUI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: bitrixregistry.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build . -t bitrixregistry.azurecr.io/bitrix-php:latest
          docker push bitrixregistry.azurecr.io/bitrix-php:latest
